### ISSUE TITLE
The .withPiplineParameter method of the ParameterBuilder class doesn't add a default value to the pipeline parameter

### ISSUE THREAD

**Issue by David-M-IBM** [cloud-native-toolkit/cdk8s-pipelines#43]
The defaultValue param of the .withPiplineParameter doesn't appear to add a default value to the pipeline params. The output is the same if it is provided a value or not.

It actually might make sense to not have the .withPipelineParameter work like that and just have it reference a pipeline param rather than generate one. There could be situations where different tasks reference the same pipeline param and it might not be a good idea for multiple tasks to have the ability to change the default value of the parent pipeline param.

**What the main.ts looks like:**
```
   .withTask(
        new TaskBuilder(this, 'task-id')
          .withStringParam(
            new ParameterBuilder('param-id').withPiplineParameter(
              'param-name',
              'param-default-value',
            ),
          )
          .withName('task-name'),
      )
```
      
**What the generated pipeline yaml looks like:**
```
kind: Pipeline
metadata:
  name: pipeline-name
spec:
  params:
    - name: param-name
      type: string
  tasks:   
    - name: task-id
          taskRef:
            name: task-name
          runAfter:
            - get-entitlement-key
          params:
            - name: param-id
              value: $(params.param-name)
```

**What the generated pipeline yaml should look like:**

```
kind: Pipeline
metadata:
  name: pipeline-name
spec:
  params:
    - name: param-name
      type: string
      default: "param-default-value"
  tasks:   
    - name: task-id
          taskRef:
            name: task-name
          runAfter:
            - get-entitlement-key
          params:
            - name: param-id
              value: $(params.param-name)
```
