### ISSUE TITLE
Add a TaskBuilder method to modify the value for the runAfter part of the task's yaml 

### ISSUE THREAD

**Issue by David-M-IBM** [cloud-native-toolkit/cdk8s-pipelines#44]
Currently there is no way to change the runAfter value of a task to have custom multiple, single, or no value, and it is always the one before it. This isn't always what you want in a pipeline, especially if you want certain tasks to run in parallel.

Adding a method to the TaskBuilder class to specify the runAfter value would solve the problem.

**An example of what the main.ts section could look like:**

>     .withTask(new TaskBuilder(this, "task-id")
>           .specifyRunAfter(["array","of","task","ids"])
>           .withName("task-name")
>       )

**An example of what the section of pipeline yaml could look like:**

```
   - name: task-id
      runAfter:
        - array
        - of
        - task
        - ids
      taskRef:
        kind: Task
        name: task-name
```
